eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
    #是否从服务注册中心获取可用的服务清单，默认为true
    fetch-registry: true
    # 是否注册到eureka中
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    #多少秒内没有发送心跳，则剔除服务列表
    lease-expiration-duration-in-seconds: 90
    #每隔多少秒向服务端发送心跳
    lease-renewal-interval-in-seconds: 3

mybatis:
  type-aliases-package: com.bowensun.domain
  mapper-locations: classpath:mapper/*.xml

spring:
  cloud:
    config:
      uri: http://localhost:8011
      profile: dev  # profile对应config server所获取的配置文件中的{profile}
      label: master # 指定Git仓库的分支，对应config server所获取的配置文件的{label}


  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://127.0.0.1:3306/film?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&useSSL=true
      username: root
      password: 285413
      #driver-class-name: oracle.jdbc.OracleDriver
      driver-class-name: com.mysql.jdbc.Driver
